# Generated by Django 5.2.6 on 2025-09-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_attendance_id_alter_authority_id_alter_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='emailid',
            field=models.CharField(max_length=200),
        ),
    ]
