# Generated by Django 5.2.6 on 2025-09-19 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_login_password_alter_login_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violence',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='violencehub',
            name='STUDENT',
        ),
        migrations.AddField(
            model_name='violence',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violencehub',
            name='photo',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
