# Generated by Django 5.2.6 on 2025-09-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_violence_photo_remove_violencehub_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violence',
            name='action',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
